version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: wefuel-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-wefuel}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./server/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - wefuel-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: wefuel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wefuel-network

  # Backend API Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: wefuel-server
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-5000}
      MONGODB_URI: ${MONGODB_URI:-mongodb://admin:password123@mongodb:27017/wefuel?authSource=admin}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      
      # Payment Gateway Configuration
      YOCO_PUBLIC_KEY: ${YOCO_PUBLIC_KEY}
      YOCO_SECRET_KEY: ${YOCO_SECRET_KEY}
      OZOW_SITE_CODE: ${OZOW_SITE_CODE}
      OZOW_PRIVATE_KEY: ${OZOW_PRIVATE_KEY}
      OZOW_API_KEY: ${OZOW_API_KEY}
      OZOW_COUNTRY_CODE: ${OZOW_COUNTRY_CODE:-ZA}
      OZOW_CURRENCY_CODE: ${OZOW_CURRENCY_CODE:-ZAR}
      
      # External Services
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      
      # Email Configuration
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      
      # Load Shedding API
      ESKOM_API_KEY: ${ESKOM_API_KEY}
      
      # Application URLs
      CLIENT_URL: ${CLIENT_URL:-http://localhost:3000}
      API_URL: ${API_URL:-http://localhost:5000}
      
      # File Upload
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - wefuel-network

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: wefuel-client
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5000}
      REACT_APP_SOCKET_URL: ${REACT_APP_SOCKET_URL:-http://localhost:5000}
      REACT_APP_YOCO_PUBLIC_KEY: ${REACT_APP_YOCO_PUBLIC_KEY}
      REACT_APP_GOOGLE_MAPS_API_KEY: ${REACT_APP_GOOGLE_MAPS_API_KEY}
      REACT_APP_GA_TRACKING_ID: ${REACT_APP_GA_TRACKING_ID}
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - wefuel-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: wefuel-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - client
      - server
    networks:
      - wefuel-network

  # PM2 Process Manager (Alternative to Docker for production)
  pm2:
    image: node:18-alpine
    container_name: wefuel-pm2
    restart: unless-stopped
    working_dir: /app
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
      - redis
    networks:
      - wefuel-network
    command: >
      sh -c "npm install -g pm2 &&
             pm2 start ecosystem.config.js &&
             pm2 logs"

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  wefuel-network:
    driver: bridge
